 name: Build and deploy Node.js app to Azure Web App
    
 on:
   push:
     branches:
       - main
   workflow_dispatch:
    
 env:
   AZURE_WEBAPP_NAME: knt-frontend   # set this to your application's name
   NODE_VERSION: '18.x'                # set this to the node version to use
   AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
    
 jobs:
   build:
     runs-on: ubuntu-latest
    
     steps:
       - uses: actions/checkout@v2
            
       - name: Set up Node.js version
         uses: actions/setup-node@v1
         with:
           node-version: ${{ env.NODE_VERSION }}
    
       - name: npm install, build
         run: |
           npm install
           npm run build --if-present
    
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v2
         with:
           name: node-app
           path: .
    
   deploy:
     runs-on: ubuntu-latest
     needs: build
     environment:
       name: 'stage'
       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
     steps:
       - name: Download artifact from build job
         uses: actions/download-artifact@v2
         with:
           name: node-app

       - uses: azure/login@v1
         with:
           creds: |
             {
               "clientId": "60873c6f-3a95-4825-bd17-3842b187b1bc",
               "clientSecret":  "lLw8Q~6AZb_p7YVbWoyQqmDEy1Rj.T3.YP6gEcO4",
               "subscriptionId": "ba35dabd-d03f-4758-8a86-8394b5cfe516",
               "tenantId": "5c494372-546d-498b-9e31-f43551cbe5ce"
             }
    
       - name: 'Deploy to Azure Web App'
         id: deploy-to-webapp
         uses: azure/webapps-deploy@v2
         with:
           app-name: ${{ env.AZURE_WEBAPP_NAME }}
           slot-name: ${{ env.AZURE_WEBAPP_SLOT_NAME }}
           package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
              
       - name: logout
         run: |
           az logout
